"""Tests for the XMP AI-provenance injection (EU AI Act Art. 50).

Pure-function coverage of ``stamp_ai_provenance`` (format surgery, gating,
idempotency, fail-open) plus one DB-integration pass proving the stamp lands —
and only lands — on AI-generated originals written through ``store_file_data``.
Mirrors the sqlite harness of ``test_media_thumbnail.py``.
"""
from __future__ import annotations

import asyncio
import io
import uuid
from datetime import datetime, timezone

import pytest
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.ext.compiler import compiles

from app import derivatives
from app.provenance import _IPTC_AI_SOURCE, stamp_ai_provenance


# ── make the Postgres-only types renderable on sqlite (test DB only) ──────────
@compiles(JSONB, "sqlite")
def _jsonb_sqlite(element, compiler, **kw):  # pragma: no cover - trivial
    return "JSON"


@compiles(UUID, "sqlite")
def _uuid_sqlite(element, compiler, **kw):  # pragma: no cover - trivial
    return "VARCHAR(36)"


from app.models import MediaItem  # noqa: E402  (after compiler registration)
from app.stores import media as media_store  # noqa: E402

_PIL = derivatives._PIL_AVAILABLE
MARKER = _IPTC_AI_SOURCE.encode("ascii")
AI_META = {"ai_generated": True, "ai_provider": "profile", "ai_model": "hero@3"}


def _image_bytes(fmt: str) -> bytes:
    from PIL import Image

    img = Image.new("RGB", (32, 24), (200, 40, 40))
    buf = io.BytesIO()
    img.save(buf, format=fmt)
    return buf.getvalue()


# ── pure function ─────────────────────────────────────────────────────────────

@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
@pytest.mark.parametrize("fmt", ["PNG", "JPEG"])
def test_stamps_ai_images_and_keeps_them_decodable(fmt):
    from PIL import Image

    original = _image_bytes(fmt)
    stamped = stamp_ai_provenance(original, AI_META)

    assert stamped != original
    assert MARKER in stamped
    assert b"profile/hero@3" in stamped
    # The pixels are untouched: same decoded size and content.
    before, after = Image.open(io.BytesIO(original)), Image.open(io.BytesIO(stamped))
    assert after.size == before.size
    assert after.tobytes() == before.tobytes()


@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
@pytest.mark.parametrize("fmt", ["PNG", "JPEG"])
def test_the_embedded_packet_is_well_formed_xmp(fmt):
    # stdlib ET is fine here: the XML under test is generated by our own
    # module two lines up, not untrusted input (no XXE surface).
    import xml.etree.ElementTree as ET

    stamped = stamp_ai_provenance(_image_bytes(fmt), AI_META)
    start = stamped.index(b"<x:xmpmeta")
    end = stamped.index(b"</x:xmpmeta>") + len(b"</x:xmpmeta>")
    root = ET.fromstring(stamped[start:end].decode("utf-8"))
    description = root.find(
        ".//{http://www.w3.org/1999/02/22-rdf-syntax-ns#}Description"
    )
    assert (
        description.get("{http://iptc.org/std/Iptc4xmpExt/2008-02-29/}DigitalSourceType")
        == _IPTC_AI_SOURCE
    )


@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
def test_stamping_is_idempotent():
    once = stamp_ai_provenance(_image_bytes("PNG"), AI_META)
    assert stamp_ai_provenance(once, AI_META) == once


@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
def test_only_ai_generated_metadata_triggers_a_stamp():
    original = _image_bytes("PNG")
    for meta in (None, {}, {"source": "manual_upload"}, {"ai_generated": "true"}):
        assert stamp_ai_provenance(original, meta) == original


def test_non_image_bytes_pass_through_untouched():
    mp4ish = b"\x00\x00\x00\x20ftypisom" + b"\x00" * 64
    assert stamp_ai_provenance(mp4ish, AI_META) == mp4ish
    assert stamp_ai_provenance(b"", AI_META) == b""


def test_corrupt_image_headers_never_raise():
    truncated_png = b"\x89PNG\r\n\x1a\n\x00\x00"
    truncated_jpeg = b"\xff\xd8\xff\xe0\xff"
    assert stamp_ai_provenance(truncated_png, AI_META) == truncated_png
    assert stamp_ai_provenance(truncated_jpeg, AI_META) == truncated_jpeg


@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
def test_webp_is_stamped_only_when_a_vp8x_header_exists():
    original = _image_bytes("WEBP")
    stamped = stamp_ai_provenance(original, AI_META)
    if b"VP8X" in original:
        assert MARKER in stamped and b"XMP " in stamped
    else:
        # Simple VP8/VP8L: reconstructing a VP8X canvas isn't worth the risk.
        assert stamped == original


# ── store integration ─────────────────────────────────────────────────────────

async def _make_factory():
    engine = create_async_engine("sqlite+aiosqlite://")
    async with engine.begin() as conn:
        await conn.run_sync(lambda c: MediaItem.__table__.create(c))
    return engine, async_sessionmaker(engine, expire_on_commit=False)


async def _seed_row(factory, user_id: str, metadata: dict) -> str:
    media_id = str(uuid.uuid4())
    async with factory() as s:
        s.add(
            MediaItem(
                id=media_id,
                user_id=user_id,
                type="image",
                prompt="p",
                file_url="/media/x.png",
                metadata_=metadata,
                name="img",
                created_at=datetime.now(timezone.utc),
            )
        )
        await s.commit()
    return media_id


@pytest.mark.skipif(not _PIL, reason="Pillow not installed")
def test_store_file_data_stamps_ai_rows_and_spares_uploads():
    async def run():
        uid = str(uuid.uuid4())
        engine, factory = await _make_factory()
        try:
            ai_id = await _seed_row(factory, uid, dict(AI_META))
            upload_id = await _seed_row(factory, uid, {"source": "manual_upload"})
            png = _image_bytes("PNG")
            async with factory() as s:
                assert await media_store.store_file_data(s, ai_id, png, "image/png", user_id=uid)
            async with factory() as s:
                assert await media_store.store_file_data(s, upload_id, png, "image/png", user_id=uid)
            async with factory() as s:
                ai_row = await s.get(MediaItem, ai_id)
                upload_row = await s.get(MediaItem, upload_id)
            assert MARKER in ai_row.file_data
            # The stamped original still thumbnails (or legitimately skips for
            # a tiny fixture) exactly like the raw one would.
            assert upload_row.file_data == png
        finally:
            await engine.dispose()

    asyncio.run(run())
